kind: Deployment
apiVersion: apps/v1
metadata:
  name: customers-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customers-api
  template:
    metadata:
      labels:
        app: customers-api
    spec:
      containers:
      - name: customers-api
        image: loadlogicacr.azurecr.io/customers-api:latest
        env:
        - name: "HOST"
          value: "0.0.0.0"
        - name: "PORT"
          value: "80"
        - name: "DATABASE_CONNECTION_STRING"
          valueFrom:
            secretKeyRef:
              name: db-connection-strings
              key: customersdb
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        livenessProbe:
          initialDelaySeconds: 45
          httpGet:
            path: /health
            port: 80
        readinessProbe:
          initialDelaySeconds: 45
          httpGet:
            path: /health
            port: 80
      imagePullSecrets:
      - name: acr-registry-secrets