apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
  labels:
    app: monitoring
spec:
  type: NodePort
  selector:
    app: monitoring
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring
  labels:
    app: monitoring
spec:
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
      - name: monitoring
        image: loadlogicacr.azurecr.io/monitoring:latest
        command:
          - "/bin/prometheus"
        args:
          - "--config.file=/etc/prometheus/prometheus.yaml"
          - "--storage.tsdb.path=/prometheus"
        resources:
          limits:
            memory: "1024Mi"
            cpu: "200m"
        ports:
        - name: http
          containerPort: 9090
      imagePullSecrets:
        - name: acr-registry-secrets