apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring
  labels:
    app: monitoring
spec:
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
      - name: monitoring
        image: loadlogicacr.azurecr.io/monitoring:latest
        imagePullSecrets:
          - name: acr-registry-secrets
        resources:
          limits:
            memory: "1024Mi"
            cpu: "200m"
        ports:
        - name: http
          containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-lb
spec:
  type: LoadBalancer
  ports:
  - port: 9090
  selector:
    app: monitoring