apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    app: rabbitmq-service
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
  - name: rabbitmq
    port: 5672
    targetPort: 5672
  - name: metrics
    port: 15692
    targetPort: 15692
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-mgmt-service
  labels:
    app: rabbitmq
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
  - name: mgmt
    port: 15672
    targetPort: 15672
    nodePort: 30002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management-alpine
        resources:
          limits:
            memory: "512Mi"
            cpu: "100m"
        ports:
        - name: rabbitmq
          containerPort: 5672
        - name: mgmt
          containerPort: 15672
        - name: metrics
          containerPort: 15692