apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management-alpine
        resources:
          limits:
            memory: "512Mi"
            cpu: "100m"
        ports:
        - name: http
          containerPort: 5672
        - name: rabbitmq-mgmt
          containerPort: 15672