apiVersion: v1
kind: Service
metadata:
  name: seq-service
  labels:
    app: seq
spec:
  type: ClusterIP
  selector:
    app: seq
  ports:
  - name: seq
    port: 5341
    targetPort: 5341
  - name: seq-ui
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: seq-ui-service
  labels:
    app: seq
spec:
  type: NodePort
  selector:
    app: seq
  ports:
  - name: seq-ui
    port: 80
    targetPort: 80
    nodePort: 30003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq
  labels:
    app: seq
spec:
  selector:
    matchLabels:
      app: seq
  template:
    metadata:
      labels:
        app: seq
    spec:
      containers:
      - name: seq
        image: datalust/seq:latest
        env:
          - name: "ACCEPT_EULA" 
            value: "Y"
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - name: seq-ui
          containerPort: 80
        - name: seq
          containerPort: 5341
