apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq
  labels:
    app: seq
spec:
  selector:
    matchLabels:
      app: seq
  template:
    metadata:
      labels:
        app: seq
    spec:
      containers:
      - name: seq
        image: datalust/seq:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "100m"
        ports:
        - name: http
          containerPort: 80