version: "3.4"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1

  kibana:
    platform: linux/amd64
    image: docker.elastic.co/kibana/kibana:7.12.1

  sqlserver:
    # image: mcr.microsoft.com/mssql/server:2017-latest
    image: mcr.microsoft.com/azure-sql-edge

  rabbitmq-service:
    image: rabbitmq:3-management-alpine

  envoy:
    image: envoyproxy/envoy:v1.16.0

  ordering-api-service:
    image: ${REGISTRY:-kt713}/ordering-api:${TAG:-latest}
    build:
      context: .
      dockerfile: services/ordering/Ordering/Dockerfile
    depends_on:
      - sqlserver
      - elasticsearch
      - rabbitmq-service

  customers-api-service:
    image: ${REGISTRY:-kt713}/customers-api:${TAG:-latest}
    build:
      context: .
      dockerfile: services/customers/Dockerfile
    depends_on:
      - sqlserver
      - elasticsearch
      - rabbitmq-service

  locations-api-service:
    image: ${REGISTRY:-kt713}/locations-api:${TAG:-latest}
    build:
      context: .
      dockerfile: services/locations/Dockerfile
    depends_on:
      - sqlserver
      - elasticsearch
      - rabbitmq-service

  userprofile-api-service:
    image: ${REGISTRY:-kt713}/userprofile-api:${TAG:-latest}
    build:
      context: .
      dockerfile: services/user-profile/Dockerfile
    depends_on:
      - sqlserver
      - elasticsearch
      - rabbitmq-service

  monitoring-service:
    image: prom/prometheus:latest
    depends_on:
      - rabbitmq-service
      - ordering-api-service
      - customers-api-service
      - locations-api-service
