version: "3.4"

services:
  seq:
    image: datalust/seq:latest

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  envoy:
    image: envoyproxy/envoy:v1.16.0

  ordering-api:
    image: ${REGISTRY:-kt713}/ordering-api:${TAG:-latest}
    build:
      context: .
      dockerfile: ordering/Ordering/Dockerfile
    depends_on:
      - sqlserver
      - seq
      - rabbitmq

  customers-api:
    image: ${REGISTRY:-kt713}/customers-api:${TAG:-latest}
    build:
      context: .
      dockerfile: customers/Dockerfile
    depends_on:
      - sqlserver
      - seq
      - rabbitmq

  locations-api:
    image: ${REGISTRY:-kt713}/locations-api:${TAG:-latest}
    build:
      context: .
      dockerfile: locations/Dockerfile
    depends_on:
      - sqlserver
      - seq
      - rabbitmq

  prometheus:
    image: prom/prometheus:latest
    depends_on:
      - rabbitmq
      - ordering-api
      - customers-api
      - locations-api
