version: "3.4"

volumes:
  loadlogic-prometheus_data:
  loadlogic-sql_data:
  loadlogic-rabbitmq_log:
  loadlogic-rabbitmq_data:

services:
  seq-service:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"

  sqlserver:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - loadlogic-sql_data:/var/opt/mssql

  rabbitmq-service:
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - loadlogic-rabbitmq_log:/var/log/rabbitmq
      - loadlogic-rabbitmq_data:/var/lib/rabbitmq

  envoy:
    ports:
      - "9901:9901"
      - "10000:10000"
    volumes:
      - ./api-gateway/:/etc/envoy/

  ordering-api-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - PORT=80
      - SEQ_SERVER_URL=${SEQ_SERVER_URL:-http://seq-service}
      - DATABASE_CONNECTION_STRING=${ORDERING_DB:-Server=sqlserver;Database=LoadLogic_OrderingDB;User Id=sa;Password=Pass@word}
      - EVENTBUS_CONNECTION_STRING=${EVENTBUS_CONNECTION_STRING:-rabbitmq-service}
      - EVENTBUS_USERNAME=${EVENTBUS_USERNAME:-guest}
      - EVENTBUS_PASSWORD=${EVENTBUS_PASSWORD:-guest}
    ports:
      - "5121:80"

  customers-api-service:
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - SEQ_SERVER_URL=${SEQ_SERVER_URL:-http://seq-service}
      - DATABASE_CONNECTION_STRING=${CUSTOMERS_DB:-sqlserver://sa:Pass@word@sqlserver?database=LoadLogic_CustomersDB}
    ports:
      - "5151:80"

  locations-api-service:
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - SEQ_SERVER_URL=${SEQ_SERVER_URL:-http://seq-service}
      - DATABASE_CONNECTION_STRING=${LOCATIONS_DB:-sqlserver://sa:Pass@word@sqlserver?database=LoadLogic_LocationsDB}
    ports:
      - "5161:80"

  monitoring-service:
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/:/etc/prometheus/
      - loadlogic-prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/prometheus"
