version: "3.4"

volumes:
  prometheus_data:
  sql_data:
  rabbitmq_log:
  rabbitmq_data:
  elasticsearch_data:

services:
  elasticsearch:
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

  sqlserver:
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  rabbitmq-service:
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_log:/var/log/rabbitmq
      - rabbitmq_data:/var/lib/rabbitmq

  envoy:
    ports:
      - "9901:9901"
      - "10000:10000"
    volumes:
      - ./api-gateway/:/etc/envoy/

  ordering-api-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - PORT=80
      - ES_SERVER_URL=${ES_SERVER_URL:-http://elasticsearch:9200}
      - DATABASE_CONNECTION_STRING=${ORDERING_DB:-Server=sqlserver;Database=LoadLogic_OrderingDB;User Id=sa;Password=Pass@word}
      - EVENTBUS_CONNECTION_STRING=${EVENTBUS_CONNECTION_STRING:-rabbitmq-service}
      - EVENTBUS_USERNAME=${EVENTBUS_USERNAME:-guest}
      - EVENTBUS_PASSWORD=${EVENTBUS_PASSWORD:-guest}
    ports:
      - "5121:80"

  customers-api-service:
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - ES_SERVER_URL=${ES_SERVER_URL:-http://elasticsearch:9200}
      - DATABASE_CONNECTION_STRING=${CUSTOMERS_DB:-sqlserver://sa:Pass@word@sqlserver?database=LoadLogic_CustomersDB}
    ports:
      - "5151:80"

  locations-api-service:
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - ES_SERVER_URL=${ES_SERVER_URL:-http://elasticsearch:9200}
      - DATABASE_CONNECTION_STRING=${LOCATIONS_DB:-sqlserver://sa:Pass@word@sqlserver?database=LoadLogic_LocationsDB}
    ports:
      - "5161:80"

  userprofile-api-service:
    environment:
      - PORT=80
      - DATABASE_CONNECTION_STRING=${USERPROFILE_DB:-jdbc:sqlserver://sqlserver;database=LoadLogic_UserProfileDB}
      - DATABASE_USERNAME=${USERPROFILE_DB_USERNAME:-sa}
      - DATABASE_PASSWORD=${USERPROFILE_DB_PASSWORD:-Pass@word}
    ports:
      - "5171:80"

  monitoring-service:
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/prometheus"
