version: "3.4"

services:
  seq:
    image: datalust/seq:latest

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  envoy:
    image: envoyproxy/envoy:v1.16.0

  # dispatching_service:
  #   image: ${REGISTRY:-kt713}/dispatching_service:${PLATFORM:-linux}-${TAG:-latest}
  #   build:
  #     context: .
  #     dockerfile: dispatching/~/Dockerfile
  #   depends_on:
  #     - sqlserver
  #     - seq
  #     - rabbitmq

  # hauling_service:
  #   image: ${REGISTRY:-kt713}/hauling_service:${PLATFORM:-linux}-${TAG:-latest}
  #   build:
  #     context: .
  #     dockerfile: hauling/~/Dockerfile
  #   depends_on:
  #     - sqlserver
  #     - seq
  #     - rabbitmq

  ordering_service:
    image: ${REGISTRY:-kt713}/ordering_service:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: ordering/Ordering/Dockerfile
    depends_on:
      - sqlserver
      - seq
      - rabbitmq

  # payments_service:
  #   image: ${REGISTRY:-kt713}/payments_service:${PLATFORM:-linux}-${TAG:-latest}
  #   build:
  #     context: .
  #     dockerfile: payments/~/Dockerfile
  #   depends_on:
  #     - sqlserver
  #     - seq
  #     - rabbitmq

  customers_service:
    image: ${REGISTRY:-kt713}/customers_service:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: customers/Dockerfile
    entrypoint:
      [
        "/dist/wait-for-it.sh",
        "sqlserver:1433",
        "-t",
        "120",
        "--",
        "/dist/customers",
      ]
    depends_on:
      - sqlserver
      - seq
      - rabbitmq

  locations_service:
    image: ${REGISTRY:-kt713}/locations_service:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: locations/Dockerfile
    entrypoint:
      [
        "/dist/wait-for-it.sh",
        "sqlserver:1433",
        "-t",
        "120",
        "--",
        "/dist/locations",
      ]
    depends_on:
      - sqlserver
      - seq
      - rabbitmq

  prometheus:
    image: prom/prometheus:latest
    depends_on:
      - rabbitmq
      - ordering_service
      - customers_service
      - locations_service
