version: "3.4"

services:
  seq-service:
    image: datalust/seq:2020.5

  sqlserver:
    # image: mcr.microsoft.com/mssql/server:2017-latest
    image: mcr.microsoft.com/azure-sql-edge

  rabbitmq-service:
    image: rabbitmq:3-management-alpine

  envoy:
    image: envoyproxy/envoy:v1.16.0

  ordering-api-service:
    image: ${REGISTRY:-kt713}/ordering-api:${TAG:-latest}
    build:
      context: .
      dockerfile: ordering/Ordering/Dockerfile
    depends_on:
      - sqlserver
      - seq-service
      - rabbitmq-service

  customers-api-service:
    image: ${REGISTRY:-kt713}/customers-api:${TAG:-latest}
    build:
      context: .
      dockerfile: customers/Dockerfile
    depends_on:
      - sqlserver
      - seq-service
      - rabbitmq-service

  locations-api-service:
    image: ${REGISTRY:-kt713}/locations-api:${TAG:-latest}
    build:
      context: .
      dockerfile: locations/Dockerfile
    depends_on:
      - sqlserver
      - seq-service
      - rabbitmq-service

  monitoring-service:
    image: prom/prometheus:latest
    depends_on:
      - rabbitmq-service
      - ordering-api-service
      - customers-api-service
      - locations-api-service
