name: api-gateway-workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/api-gateway/**"

jobs:
  build:
    name: Build & Push Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        uses: docker/login-action@v1 
        with:
          registry: loadlogicacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./src
          file: ./src/api-gateway/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: loadlogicacr.azurecr.io/api-gateway:latest
